name: github-actions
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  make-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install
